languageCode = "en-us"
title = "My new blog, powered by ğŸ´ Horseman"
baseURL = "/"
themesDir = "themes"
theme = "hugo-casper3"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
author = "authors"
tag = "tags"

[params]
google_analytics_id = ""
twitter = "@ceruthedev"
showAuthorOnHomepage = false
showAuthorOnPosts = false
showPostsOnHomepage = true
addFrame = true
addDot = true
SiteName = "ğŸ´ Horseman Blog"
sitename = "ğŸ´ Horseman Blog"
