languageCode = 'en-us'
title = 'My new blog, powered by ğŸ´ Horseman'
baseURL = "/"
themesDir = "themes"
theme = "hugo-casper3"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  google_analytics_id = ""
  twitter_handle = "@ceruthedev"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addFrame = true
  addDot = true